### ISSUE TITLE
Create prototype for Employers > Add Job Post > Payment Form

### ISSUE THREAD

**Issue by thomaspcleary** [thomaspcleary/careercenter#17]

**Comment by thomaspcleary** [comment]
Payment form should have just a static price ($350 members/$500 non-members) and ability to enter in a discount code.

**Comment by thomaspcleary** [comment]
@epkatz225 - Swap the credit card and billing info sections, and add ability to enter discount code at time of selecting package - we need to reflect the price/charge in real-time in the credit card section ie.) Total: $315

**Comment by epkatz225** [comment]
@thomaspcleary Since they are logged in, won't we be able to tell if they are Members or not?  Therefore wouldn't need to choose Member or Non-member pricing as an option.  Also, I was able to change the price based on checkboxes, but not based on value of Promo Code box on employers-payment-form.html

**Comment by thomaspcleary** [comment]
Correct $ would appear static, driven from the DB based on member status.

**Comment by epkatz225** [comment]
![employers-payment-form](https://user-images.githubusercontent.com/35513796/36070209-5830c446-0ec4-11e8-8d5d-bf28f0d3e150.png)
